In [1]:
import numpy as np

In [2]:
#definicion de variables
E=95
nu=0.07
mu=E/(2*(1+nu))
K=E/(3*(1-2*nu))

In [3]:
#coeficientes
c11=K+4/3*mu
c22=c11
c33=c11
c12=K-2/3*mu
c13=c12
c21=c12
c23=c21
c32=c23
c31=c13
c44=mu
c55=mu
c66=mu
c44=mu

In [4]:
#matriz de rigidez
R=np.array([[c11, c12, c13, 0, 0, 0],
            [c21, c22, c23, 0, 0, 0],
            [c31, c32, c33, 0, 0, 0],
            [0, 0, 0, c44, 0, 0],
            [0, 0, 0, 0, c55, 0],
            [0, 0, 0, 0, 0, c66]
            ])
np.round(R,4)

array([[96.0117,  7.2267,  7.2267,  0.    ,  0.    ,  0.    ],
       [ 7.2267, 96.0117,  7.2267,  0.    ,  0.    ,  0.    ],
       [ 7.2267,  7.2267, 96.0117,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , 44.3925,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    , 44.3925,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    , 44.3925]])

In [5]:
#matriz de complianza
c=np.array([[1, -nu, -nu, 0, 0, 0],
            [-nu, 1, -nu, 0, 0, 0],
            [-nu, -nu, 1, 0, 0, 0],
            [0, 0, 0, 2*(1+nu), 0, 0],
            [0, 0, 0, 0, 2*(1+nu), 0],
            [0, 0, 0, 0, 0, 2*(1+nu)]
            ])
C=(1/E)*c
np.round(C,4)

array([[ 0.0105, -0.0007, -0.0007,  0.    ,  0.    ,  0.    ],
       [-0.0007,  0.0105, -0.0007,  0.    ,  0.    ,  0.    ],
       [-0.0007, -0.0007,  0.0105,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.0225,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.0225,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.0225]])

In [6]:
np.round(C*R)

array([[ 1., -0., -0.,  0.,  0.,  0.],
       [-0.,  1., -0.,  0.,  0.,  0.],
       [-0., -0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])